name = "MPIAsyncPools"
uuid = "71dbed6d-20b0-48c6-bb22-c3e423edce76"
authors = ["Albin Severinson <albin@severinson.org> and contributors"]
version = "0.2.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
MPI = "0.15 - 0.19"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
